libname bdregion 'G:\数据恢复\No.3 [NTFS]\ 根目录\Box Sync\cdc\big data\region_sasfiles';
run;
*disease ranking;
data a;
set bdregion.total;
where year ge 2006 and fips eq '00000000' and month eq 0 and did ne 0 and category in ("1","2","22");
run; 
proc sort data=a;
by  year descending incidence;
run;
data rank;
set a;
by year;
if first.year then rank_h1 = 0;
rank_h1 + 1 ;
drop fips month province did category population transmission pathogen;
run;
data top5;
set rank;
where rank_h1 in (1:5);
run;

*top disease province 5;
data province;
set bdregion.total;
where year ge 2006 and fips ne '00000000' and month eq 0 and did in (2600,302);
drop fips month category population transmission pathogen;
run; 
proc sort data=province;
by year did descending incidence;
run;
proc rank data=province out=rankp  descending ;
var  incidence;
by  year did ;
ranks  rankp;
run;
data topp5;
set rankp;
where rankp in (1:5);
run;


proc sort data=province;
by year did descending mortality;
run;
proc rank data=province out=rankp  descending ;
var  mortality;
by  year did ;
ranks  rankp;
run;
data topp5;
set rankp;
where rankp in (1:5);
run;
